Repository 2110336-2565-2/sec33_Group4_BookBix_Frontend, pull requests merged in 2023-03, with the labels that each got.

#17 ➕ Add fonts and import to styles.scss
  src/assets/scss/abstracts/_fonts.scss
  src/assets/scss/abstracts/_index.scss
  src/assets/scss/style.scss
Labels: enhancement

#19 ✅Implement feature/logged-in-history
  src/assets/scss/abstracts/_colors.scss
  src/assets/scss/components/_loggedinhistory.scss
  src/assets/scss/style.scss
  src/components/CustomTable.tsx
  src/interfaces/history.interface.ts
  src/routes/App.tsx
  src/screens/LoggedInHistory.tsx
  src/screens/index.tsx
Labels: enhancement

#23 🔋Update API path for register
  src/components/LoginRegister.tsx
Labels: invalid

#18 Create the summary page of bookings
  package-lock.json
  package.json
  src/assets/scss/abstracts/_colors.scss
  src/assets/scss/abstracts/_index.scss
  src/assets/scss/abstracts/_screenSizes.scss
  src/assets/scss/components/_bookingsSummary.scss
  src/assets/scss/style.scss
  src/components/RowBooking.tsx
  src/components/TicketBooking.tsx
  src/interfaces/booking.interfaces.ts
  src/routes/App.tsx
  src/screens/BookingsSummary.tsx
  src/screens/index.tsx
  src/utils/Booking.utils.tsx
  src/utils/Time.utils.ts
Labels: enhancement

#20 Create the navigation bar
  src/assets/scss/abstracts/_screenSizes.scss
  src/assets/scss/components/_navBar.scss
  src/assets/scss/style.scss
  src/components/LoginRegister.tsx
  src/components/Navbar.tsx
  src/hooks/CustomProvider.tsx
  src/interfaces/user.interfaces.ts
  src/routes/App.tsx
  src/screens/Home.tsx
  src/screens/Login.tsx
Labels: enhancement

#24 Fix a little bug about navBar
  src/assets/scss/style.scss
Labels: bug

#27 🐱‍👓Implement review v.1
  package-lock.json
  package.json
  src/assets/scss/abstracts/_colors.scss
  src/assets/scss/components/_bookingsSummary.scss
  src/assets/scss/components/_customModal.scss
  src/assets/scss/style.scss
  src/components/CustomButton.tsx
  src/components/CustomModal.tsx
  src/components/RowBooking.tsx
  src/components/TicketBooking.tsx
  src/interfaces/cookie.interfaces.ts
  src/interfaces/reviews.interfaces.ts
  src/main.tsx
  src/routes/App.tsx
  src/utils/Booking.utils.tsx
Labels: enhancement

#28 Fix layout and api
  src/assets/scss/components/_booklocation.scss
  src/components/Review.tsx
  src/screens/BookLocation.tsx
  src/screens/ManageProfile.tsx
  src/utils/Time.utils.ts
Labels: bug

#29 📥 Fixed Many Bug and Restructure Some Code
  src/assets/scss/components/_index.scss
  src/assets/scss/components/authentication/_forgetpassword.scss
  src/assets/scss/components/authentication/_index.scss
  src/assets/scss/components/authentication/_login.scss
  src/assets/scss/components/authentication/_register.scss
  src/assets/scss/components/authentication/_resetpassword.scss
  src/assets/scss/style.scss
  src/components/Authentication.tsx
  src/components/CustomButton.tsx
  src/components/CustomModal.tsx
  src/components/Navbar.tsx
  src/components/RowBooking.tsx
  src/components/SearchCard.tsx
  src/components/TicketBooking.tsx
  src/hooks/CustomProvider.tsx
  src/interfaces/authentication.interface.ts
  src/interfaces/booking.interfaces.ts
  src/interfaces/cookie.interfaces.ts
  src/interfaces/route.interface.ts
  src/interfaces/user.interfaces.ts
  src/routes/App.tsx
  src/screens/BookingsSummary.tsx
  src/screens/ForgetPassword.tsx
  src/screens/LoggedInHistory.tsx
  src/screens/Login.tsx
  src/screens/ManageProfile.tsx
  src/screens/Register.tsx
  src/screens/ResetPassword.tsx
  src/utils/Booking.utils.tsx
  src/utils/authentication.utils.ts
Labels: bug, enhancement

#30 📥 Create 404 Not Found Page
  src/assets/images/Delorean.webp
  src/assets/images/backToTheHomepage.webp
  src/assets/scss/abstracts/_colors.scss
  src/assets/scss/components/_index.scss
  src/assets/scss/components/_notFound.scss
  src/interfaces/route.interface.ts
  src/routes/App.tsx
  src/screens/Home.tsx
  src/screens/NotFound.tsx
  src/screens/index.tsx
Labels: enhancement
